default:
  target: dev

  outputs:
    dev:
      type: bigquery
      method: service-account
      project: thelook-ecommerce-dbt-455408     # ← Your real GCP project ID
      dataset: dbt_bwan                         # ← Dev dataset
      threads: 4
      timeout_seconds: 300
      location: US
      keyfile: "C:\\repo\\dbt-theLookECommerce\\thelook-ecommerce-dbt-455408-d274588b2b06.json"


    prod:
      type: bigquery
      method: service-account
      project: thelook-ecommerce-dbt-455408     # ← Same GCP project
      dataset: dbt                              # ← Prod dataset
      threads: 4
      timeout_seconds: 300
      location: US
      keyfile: "C:\\repo\\dbt-theLookECommerce\\thelook-ecommerce-dbt-455408-d274588b2b06.json"


