
version: 2

models:
  - name: stg_events
    description: "Staging model for events table"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - not_null
          - unique
